services:
  - type: web
    name: rag-api
    env: python
    plan: starter
    healthCheckPath: /health
    buildCommand: |
      pip install -r requirements.txt
      python - <<'PY'
from sentence_transformers import CrossEncoder
CrossEncoder("BAAI/bge-reranker-base")
print("Reranker preloaded")
PY
    startCommand: uvicorn rag_app.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: OPENAI_EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: DATA_DIR
        value: data
