services:
  - type: web
    name: debt-agreement-analysis
    env: python
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Listing contents:"
      ls -la
      echo "Installing Python dependencies..."
      pip install -r rag_app/requirements.txt
      echo "Navigating to frontend directory..."
      cd rag-frontend
      echo "Current directory: $(pwd)"
      echo "Listing frontend contents:"
      ls -la
      echo "Installing Node dependencies..."
      npm install
      echo "Building frontend..."
      npm run build
      echo "Checking build output:"
      ls -la build/
      echo "Creating static directory..."
      mkdir -p ../rag_app/static
      echo "Copying build files..."
      cp -r build/* ../rag_app/static/
      echo "Verifying copy:"
      ls -la ../rag_app/static/
    startCommand: cd rag_app && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18
    healthCheckPath: /health
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self';"
